### ISSUE TITLE
Generating .d.ts files in examples

### ISSUE THREAD

**Issue by sr258** [boyum/h5p-types#637] opened 2023-12-23 13:30 UTC
Hi,

I find the examples very useful, but it's unclear to me, how to create and update the .d.ts files in the root directory (semantics.json.d.ts, library.json.d.ts). Do I have to update them manually or is there some tooling for generating them?

**Comment by boyum** [comment] 2023-12-23 15:28
Hi! In the examples I use [unplugin-json-dts](https://www.npmjs.com/package/unplugin-json-dts) to generate .d.ts files on build (both with webpack and Vite).

Even though this feels slightly hacky, I prefer it to not having declarations for the json files. One could also gitignore these files, as is done in Astro projects, but I've added them to version control to remove some magic.

In regards to your question itself: If you wonder, I'm sure others do too. I think we should document this more clearly.

**Comment by boyum** [comment] 2023-12-23 15:29
Whst do you think about this, by the way? Do you think it's too far from ordinary H5P development?

**Comment by sr258** [comment] 2023-12-23 15:44
Ok, I see. For me the .d.ts files aren't generate for me when running vite, neither in watch mode nor in build mode. When I deleted the .d.ts files, they aren't replaced. 

I think having typings for semantics is really useful! I believe that types tremendously increase code quality and reliability, and it's really makes sense to have a way of bringing the semantics into the code.

I've struggled a bit with running the example, btw, as they are part of the monorepo with NPM workspaces. You can't simply clone the repo and install and build the sample, but have to copy the sample directory to some other place.

**Comment by boyum** [comment] 2023-12-23 16:31
>For me the .d.ts files aren't generate for me when running vite, neither in watch mode nor in build mode. When I deleted the .d.ts files, they aren't replaced.

You might need to import semantics/library in runtime space, not only type space, for instance by using regular `import` and `verbatimModuleSyntax: true`, or by using semantics/library in the actual code. I've sometimes achieved this by simply adding a no-op:

```ts
import semantics from "./semantics.json";

semantics;
```

>I've struggled a bit with running the example, btw, as they are part of the monorepo with NPM workspaces. You can't simply clone the repo and install and build the sample, but have to copy the sample directory to some other place.

This is troublesome. I'm able to run them from the monorepo and haven't thought much about it since it's been working for me. Can you take me through the steps you follow when cloning the monorepo and trying to build the example projects? Do you run `npm run build` from the root or from the examples themselves? Both should work, I'm just curious.

**Comment by sr258** [comment] 2023-12-23 17:13
> > For me the .d.ts files aren't generate for me when running vite, neither in watch mode nor in build mode. When I deleted the .d.ts files, they aren't replaced.
> 
> You might need to import semantics/library in runtime space, not only type space, for instance by using regular `import` and `verbatimModuleSyntax: true`, or by using semantics/library in the actual code. I've sometimes achieved this by simply adding a no-op:
> 
> ```ts
> import semantics from "./semantics.json";
> 
> semantics;
> ```

The no-op works! Thanks!

>  > I've struggled a bit with running the example, btw, as they are part of the monorepo with NPM workspaces. You can't simply clone the repo and install and build the sample, but have to copy the sample directory to some other place.
> 
> This is worrysome. I'm able to run them from the monorepo and haven't thought much about it since it's been working for me. Can you take me through the steps you follow when cloning the monorepo and trying to build the example projects? Do you run `npm run build` from the root or from the examples themselves? Both should work, I'm just curious.

Here are steps to reproduce:

```sh
git clone https://github.com/boyum/h5p-types.git     # in new directory
cd h5p-types/examples/h5p-content-type-vite
npm i
npm run build
```

Result: `sh: vite: command not found`

I don't have vite installed globally, as I try to avoid having global NPM packages whenever possible. So I install vite into the repo:

```sh
npm i -D vite
npm run build
```

Then I get:
```
[commonjs--resolver] Failed to resolve entry for package "h5p-utils". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "h5p-utils". The package may have incorrect main/module/exports specified in its package.json.
```

At this point, I've copied moved the example directory out of the monorepo.

**Comment by sr258** [comment] 2023-12-23 17:17
P.S.: If I run `npm i && npm run build` in the root of the monorepo, I can build the example all right. It would probably be better for people who want to try the examples, if they are "self-contained" and not NPM workspaces.

**Comment by boyum** [comment] 2023-12-23 18:13
Thank you! I'll have to think this one through and will have a look to see how it's done in other projects. The examples serve as regression tests as well and I would rather have them as part of the monorepo.

**Comment by boyum** [comment] 2023-12-26 18:58
As the root issue was solved, would it be ok if I close this issue, @sr258?

**Closed** 2024-02-17 17:38 UTC
